---
- hosts: localhost
  vars:
    mytext: "|
     | Default ipv4 settings | SETTINGS |
     | ------ | ------ |
     | address | {{ ansible_default_ipv4.address }} | 
     | alias | {{ ansible_default_ipv4.alias }} |
     | broadcast | {{ ansible_default_ipv4.broadcast }} | 
     | gateway | {{ ansible_default_ipv4.gateway }} | 
     | interface | {{ ansible_default_ipv4.interface }} | 
     | macaddress| {{ ansible_default_ipv4.macaddress }} |
     | mtu | {{ ansible_default_ipv4.mtu }} |
     | netmask |{{ ansible_default_ipv4.netmask }} | 
     | network | {{ ansible_default_ipv4.network }} | 
     | type |{{ ansible_default_ipv4.type }} | "
    variable_name: mytext_name
  tasks:
    - copy:
        dest: ./mytext.part
        content: "{{ mytext }} , variable_name"