---
- name: test items2dict
  hosts: localhost
  vars:
   fruits:
     - fruit: apple
       color: red
     - fruit: pear
       color: yellow
     - fruit: grapefruit
       color: yellow

  tasks:
   
   - name: debug items to dict
     debug:
       msg: "{{ fruits | items2dict(key_name='fruit', value_name='color') }}"

