---
- name: test items2dict
  hosts: localhost
  pre_tasks:
    - name: Define local host/path for ease of use.
      set_fact:
        base_path: "{{ playbook_dir }}/ansible-playbooks.wiki/{{ ansible_fqdn }}" #"ansible-playbooks.wiki/{{ ansible_fqdn }}"
        today: "{{ ansible_date_time.date }}"
        anchors: "\n * [Running Processes](#running-processes)  \n * [Installed Packages](#installed-packages)  \n * [Upgradable Packages](#upgradable-packages)  \n * [Diskspace Usage DF](#diskspace-usage)  \n * [Diskspace usage  ansible_mounts](#diskspace-usage-ansiblemounts)  \n * [Ansible Facts](#ansible-facts)  \n"
   
  vars:
   fruits:
     - fruit: apple
       color: red
     - fruit: pear
       color: yellow
     - fruit: grapefruit
       color: yellow

   parts_to_md: 
    - parts: |
       | Default ipv4 settings | SETTINGS |
       | ------ | ------ |
       | address | {{ ansible_default_ipv4.address }} | 
       | alias | {{ ansible_default_ipv4.alias }} |
       | broadcast | {{ ansible_default_ipv4.broadcast }} | 
       | gateway | {{ ansible_default_ipv4.gateway }} | 
       | interface | {{ ansible_default_ipv4.interface }} | 
       | macaddress| {{ ansible_default_ipv4.macaddress }} |
       | mtu | {{ ansible_default_ipv4.mtu }} |
       | netmask |{{ ansible_default_ipv4.netmask }} | 
       | network | {{ ansible_default_ipv4.network }} | 
       | type |{{ ansible_default_ipv4.type }} | 
      variable_name: 03_ipv4data
    - parts: "testart"
      variable_name: 04_testardata
    - parts: '# {{ ansible_fqdn }} as of {{ today }}'          
      variable_name: 01_fqdn
    - parts: " {{ anchors }} "
      variable_name: 02_anchors 
    - parts: '### Running Processes:"' 
      variable_name: 05_running_processes_aheader
    - parts: Fake processes
      variable_name: 05_running_processes_bdata
    - parts: "```yaml \n {{ ansible_facts['devices'] | to_nice_yaml  }} \n```  \n"
    # ansible_facts.ansible_devices.keys() | map('regex_search', 'sd.*') | select('string') | list #"{{ ansible_devices.keys() }} | map('regex_search', 'sd.*') | select('string') | list "
      variable_name: 06_disks
  tasks:
 
  # debug it if verbosity is -vvv
   - name: debug sorted_parts
     debug:
       msg: "{{item.parts}} {{ item.variable_name }}"
       verbosity: 3
     with_items:
      - "{{parts_to_md}}"


   - name: Ensure necessary directory exists.
     file:
       name: "{{ base_path }}"
       state: directory
       mode: "0750"
       force: true
     delegate_to: localhost
     connection: local
     become: false

   - name:  Write outputs to files
     copy:
      dest: "{{ base_path }}/{{ item.variable_name }}.part"
      content: "{{ item.parts}}"
     delegate_to: localhost
     connection: local
     become: false
     with_items:
       - "{{parts_to_md}}"

   - name: Concatenate created page files.
     assemble:
       src: "{{ base_path }}"
       dest: "{{ base_path }}.md"
     delegate_to: localhost
     connection: local
     become: false
   
   #- name: Purge .part files
   #  file:
   #    name: "{{ base_path }}"
   #    state: absent
   #  delegate_to: localhost
   #  connection: local
   #  become: false

